apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: metrics-operator
  namespace: istio-system
spec:
  values:
    telemetry:
      v2:
        prometheus:
          configOverride:
            inboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url: request.url_path
                    destination_port: string(destination.port)
            outboundSidecar:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url: request.url_path
                    destination_port: string(destination.port)
            gateway:
              metrics:
                - name: requests_total
                  dimensions:
                    request_url: request.url_path
                    destination_port: string(destination.port)
