apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "service.fullname" . }}
  namespace: {{ include "service.fullname" . }}
  labels:
    name: {{ include "service.fullname" . }}
    repo: {{ include "service.fullname" . }}